spring:
  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/moviemates
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
      show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 57356930204-dusjt6grmleqhi0tk8lsaeo0d3plglh3.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://localhost:8080
            scope:
              - profile
              - email
  profiles:
    include: oauth2
    timezone: UTC
    mysql:
      init-mode: always
  server:
    port: 8080
